= MySQL Error Access Denied For Root User in Ubuntu Linux

Cuando intentamos acceder a MySql y obtenemos el siguiente error.
    
    ERROR 1698 (28000): Access denied for user 'root'@'localhost'
    
A continuacion podemos hacer lo siguiente, ingresamos a la terminal y con permisos de admin tecleamos.

    sudo mysql -u root
    "<contraseña root>"

Una vez dentro de la linea de comandos de MySQL igitamos el siguiente comando para modificar los persmisos y contraseña
del usuario root

    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';

O si queremos asignarle una contraseña lo hacemos así:

    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';


== Crear Nuevo usuario

Otra opcion es dar de alta a nuestro usuario en los usuarios de mysql server.

       sudo mysql -u root -p
       
 Dentro de la consola de mysql hacemos:
 
       mysql> use mysql;
       mysql> select user, host, plugin from mysql.user;
       mysql> create user 'username'@'localhost' identified by 'new_password';
       mysql> grant all privileges on *.* to 'username'@'localhost';
       mysql> update user set plugin = "auth_socket" where user='username';
       mysql> flush privileges;
       mysql> exit;
       mysql> sudo service mysql restart
       
Otra opcion seria cambiar el plugin del root user 
            
        $ sudo mysql -u root -p
        
        mysql> use mysql
        mysql> select user, host, plugin from mysql.user;
        mysql> update user set plugin="mysql_native_password" where User="root";
        mysql> flush privileges;
        mysql> exit;
